@startuml
'https://plantuml.com/component-diagram
!include <logos/go>
!include <logos/java>
!include <logos/react>
!include <logos/typescript>
!include <logos/raspberry-pi>
!include <logos/python>
!include <logos/mongodb>
!include <logos/macos>

title CAG Contactor's pump foil experience
footer CAG Contator 2025

package "Pump foil" {
 rectangle MPU6050[
    MPU-6050
    ---
    sensor with a
    3-axes accelerometer
    and a 3-axes gyroscope
 ]
  rectangle "<$raspberry-pi><$python>\nRaspberry PI" as Pi
  Pi - [MPU6050]: I2C
}

rectangle "Mac mini" as Mac {
    package "Game frontend" {
        rectangle "<:surfer:>\n<$typescript>\nExcalibur.js as\ngame engine" as GameFront
    }


    package "Backend" {
        rectangle "<$go>\nGame status &\nPlayer registration" as Back
    }

    package "Database" {
        rectangle "<$mongodb>" as DB
    }

    package "Registration frontend" {
        rectangle "<$react>\nAdmin frontend" as RegFront
    }
}
package "QR Scanner" {
   rectangle "<:camera:>\nCamera" as Camera
  rectangle "<$raspberry-pi><$java>\nRaspberry PI" as CameraPi
    CameraPi - Camera: USB
}

Pi-up->GameFront : WebSocket
GameFront -- Back: REST
Back -- DB: Players\ntimes
RegFront -left- Back: REST
CameraPi -- Back: REST

:User:-left- RegFront
:User:-up- Camera



@enduml